server:
  port: 8088

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      partnerAPI:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      contatosAPI:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic
#        requestInterceptors:
#          - com.feignstudy.demo.interceptors.ContatosApiInterceptor

contatosAPI:
  host: http://localhost:3000/

partnerAPI:
  host: http://localhost:8085/webhook

app:
  viacep:
    host: https://viacep.com.br